services:
  app:
    entrypoint:
      - sleep
      - infinity
    image: wgetmeoh/rust-lang-dev-env:debian
    init: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - type: bind
        source: ./
        target: /com.docker.devenvironments.code
